### ISSUE TITLE
Please add open source license

### ISSUE THREAD

**Issue by kapasiuj** [programmingwithswift/SwiftUIStopWatch#1]
I was hoping to modify and reuse your code for a project I'm working on, but this is not allowed since the code in this repo is not licensed.

According to the github docs : https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license

> `However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.`

Thanks!

**Comment by kapasiuj** [comment]
I've decided to write one from scratch, I don't need to reuse this code anymore. Closing this issue. Thanks.

**Comment by programmingwithswift** [comment]
Hey @kapasiuj, sorry, I completely missed this email. This is a good point, I need to update all the repos so that they are free and open source.
